name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Chromium extension
        run: |
          mkdir -p dist/chromium
          cp -r src/* dist/chromium/
          cd dist/chromium
          rm -rf manifest-firefox.json
          zip -r ../jump-to-tabn-chromium.zip .
          cd ../..

      - name: Build Firefox extension
        run: |
          mkdir -p dist/firefox
          cp -r src/* dist/firefox/
          cd dist/firefox
          mv manifest-firefox.json manifest.json
          zip -r ../jump-to-tabn-firefox.zip .
          cd ../..

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/jump-to-tabn-chromium.zip
            dist/jump-to-tabn-firefox.zip
